# Generated by Django 4.2.2 on 2023-06-23 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import utils.upload_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='slug')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('active', models.BooleanField(default=False, verbose_name='active/inactive')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_product.categories', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('image', models.ImageField(upload_to=utils.upload_image.upload_image_path, verbose_name='main image')),
                ('inventory', models.IntegerField(default=10, verbose_name='inventory')),
                ('short_description', models.TextField(max_length=700, verbose_name='short description')),
                ('full_description', models.TextField(verbose_name='full description')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('active', models.BooleanField(default=False, verbose_name='active/inactive')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_product.categories', verbose_name='category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL, verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('active', models.BooleanField(default=True, verbose_name='inactive/active')),
                ('products', models.ManyToManyField(blank=True, related_name='tags', to='shop_product.products', verbose_name='products')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='ProductsGalleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('image', models.ImageField(upload_to=utils.upload_image.upload_image_path, verbose_name='image')),
                ('active', models.BooleanField(default=False, verbose_name='active / inactive')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop_product.products', verbose_name='product')),
            ],
            options={
                'verbose_name': 'products gallery',
                'verbose_name_plural': 'products galleries',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveBigIntegerField(default=0, verbose_name='price')),
                ('off_price', models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='off price')),
                ('off_expired_time', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='off expired time')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='shop_product.products', verbose_name='product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'product price',
                'verbose_name_plural': 'products prices',
            },
        ),
    ]
