# Generated by Django 4.2.2 on 2023-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active/inactive'),
        ),
        migrations.AlterField(
            model_name='products',
            name='inventory',
            field=models.IntegerField(default=10, verbose_name='inventory'),
        ),
    ]
